---
title: "Table + Data Diff Summary"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(kableExtra)
library(tibble)
library(reticulate)
library(shiny)
library(daff)
library(reactable)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# custom scripts
source(here::here("R", "utils.R"))
source(here::here("R", "setup-cache.R"))
source(here::here("R", "knitr-hooks.R"))
source(here::here("R", "diffing.R"))
# install knitr hooks
install_knitr_hooks()
home_path <- here::here("inst/tutorials/data_diff/data/")
pew_data_path <- paste0(home_path, "pew.csv")
nba_data_path <- paste0(home_path, "nba.csv")
rpew <- read.csv(pew_data_path)
rnba <- read.csv(nba_data_path)
tutorial_options(exercise.timelimit = 120)
```

## POC for data diff (worked example)

```{python poc_setup, echo=TRUE}
import pandas as pd
# sadly we have to define all of the python data for the exercise setup and the 
# diff to work with the shiny
# for pew exercises
pew = pd.read_csv(r.pew_data_path)
pew_long = pd.melt(pew, id_vars='religion')

# for poc for diff
y = r.mtcars.iloc[0:3, ]
x = y.copy()
x = x.head(2) # remove a row
x.loc['Mazda RX4', 'mpg'] = 10 # change a value
x['hello'] = "world"  # add a column
del x['disp'] # remove a column
```

Shiny example:

```{python y, echo=TRUE, opts.label="pprinter"}
# TODO make sure we don't NEED an exercise to pprint
y
```

<!-- ```{python x, echo=TRUE, opts.label="pprinter"} -->
<!-- x -->
<!-- ``` -->


<!-- These makes it so that the x and y data are SharedData so that reactable can detect it -->
<!-- `r htmltools::knit_print.shiny.tag.list(reactable::reactable(py$x))` -->
<!-- `r htmltools::knit_print.shiny.tag.list(reactable::reactable(py$y))` -->

DIFF:

```{r context="render"}
shiny::fluidPage(
  fluidRow(
    reactable::reactableOutput("summary"),
    br(),
    reactable::reactableOutput("datadiff")
  )
)
```


```{r poc_daff, context="server", results="asis"}
# get the diff
y <- py$y
x <- py$x
diff <- diff_data(y, x)
s <- attr(diff, "summary")
s <- purrr::map_df(s, ~ as.character(.))

# reactable output 
output$summary <- reactable::renderReactable(
  diff_summary_html(s, reactable_output = TRUE)
)
output$datadiff <- reactable::renderReactable(
  daff_html(y, x, include_diff_table = TRUE, reactable_output = TRUE)
)

```

## `pd.melt`

### Data

```{python pew_setup}
import pandas as pd
import os
pew = pd.read_csv(r.pew_data_path)
pew_long = pd.melt(pew, id_vars='religion')

nba = pd.read_csv(r.nba_data_path)
```

I have already loaded up the data for you to a variable called `pew`. Run the exercise below to take a peek at the data:

```{python ex-read_pew, exercise=TRUE, exercise.setup="pew_setup", opts.label="pprinter"}
pew

```

Execute the following `melt` operation:

This commented line is necessary for reactable to render the pew dfs

```{python ex-pew_long, debug=FALSE, exercise=TRUE, exercise.setup="pew_setup", opts.label="pprinter"}
pew_long = pd.melt(pew, id_vars='religion')
pew_long

```

<!-- TODO: try out the modern pandas tidy data series: https://tomaugspurger.github.io/modern-5-tidy -->

Let's look at what happened more closely:

```{r context="render"}
shiny::fluidPage(
  fluidRow(
    reactable::reactableOutput("pew_summary"),
    br(),
    reactable::reactableOutput("pew_datadiff")
  )
)
```

```{r pew_diff_server, context="server", results="asis"}
# get the diff
# TODO think about better ways to do this worked example flow dynamically.
y <- py$pew
x <- py$pew_long
diff <- diff_data(y,  x)
s <- attr(diff, "summary")
s <- purrr::map_df(s, ~ as.character(.))

# reactable output
output$pew_summary <- reactable::renderReactable(
  diff_summary_html(s, reactable_output = TRUE)
)
output$pew_datadiff <- reactable::renderReactable(
  daff_html(y, x, include_diff_table = TRUE, reactable_output = TRUE)
)
```

<!-- ```{python ex-nba-load, exercise=TRUE, exercise.setup="pew_setup", opts.label="pprinter"} -->
<!-- nba -->

<!-- ``` -->


















