---
title: "lolviz"
output: html_document
runtime: shiny
---

```{r opts.label = "dsvizi"}
fluidPage(
  textInput("lang_x", label = h2("Visualize Python Data Structure:"), value = "[1, 2, 3]"),
  # textInput("lang_y", label = "Lang Y", value = "Enter second expression."),
  hr(),
  DiagrammeR::grVizOutput('diagrammer', width = "25%", height = "10%")
)
```

```{r echo=FALSE, context="server"}
lolviz <- reticulate::import("lolviz", convert=FALSE)
python_code <- shiny::renderText({ input$lang_x })
lolviz$objviz(python_code)$render(view = FALSE)
# wrap the lolviz into a reactive expression
result <- shiny::reactive(
  lolviz$objviz(
    tryCatch(
      reticulate::py_eval(
        shiny::renderText({ input$lang_x })()
      ),
      error = function(e) ""
    )
  )$source
)
# output for diagram
output$diagrammer <-
  DiagrammeR::renderGrViz(
    DiagrammeR::grViz(
      # use the reactive result when it's available and update diagram
      diagram = as.character(result())
    )
  )
# TODO figure out how to do a clean up of files upon exit
```
